name: accessiblecity
description: "Accessible City app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+2

environment:
  sdk: '>=3.3.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  provider:
  uuid: ^4.4.0
  intl: ^0.19.0
  url_launcher: ^6.3.1
  maplibre_gl: ^0.24.1 #0.22.0
  flutter_map: ^7.0.2
  vector_map_tiles: ^8.0.0
  vector_map_tiles_mbtiles: ^1.2.0
  vector_tile_renderer: ^5.2.1
  latlong2: ^0.9.1
  sqlite3_flutter_libs: ^0.5.41
  mbtiles: ^0.4.2
  path_provider: ^2.1.3
  archive: ^3.6.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  rsa_encrypt: ^2.0.0
  pointycastle: ^3.9.1
  http: ^1.2.2
  location: ^8.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  app_settings: ^5.1.1
  flutter_logs: ^2.2.1
  package_info_plus: ^9.0.0

dev_dependencies:
  build_info_generator:
    path: ./build_info_generator
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: InclusiveSans
      fonts:
        - asset: assets/fonts/InclusiveSans/InclusiveSans-VariableFont_wght.ttf
        - asset: assets/fonts/InclusiveSans/InclusiveSans-Italic-VariableFont_wght.ttf
          style: italic
    - family: BarlowCondensed
      fonts:
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Black.ttf
          weight: 900
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-BlackItalic.ttf
          weight: 900
          style: italic

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/map-font.zip
    - assets/cologne.zip
    - assets/oberhausen.zip
    - assets/map-style-template.json
    - assets/buildinfo.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 31 # android min sdk min:16, default 21
  remove_alpha_ios: true
  adaptive_icon_background: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"